### ISSUE TITLE
Change prev next buttons

### ISSUE THREAD

**Issue by bobiblazeski** [bobiblazeski/react-3d-carousel#2]
The prev/next buttons look a bit tacky. Might as well replace them with something neat and simple. :)

**Comment by bebraw** [comment]
Consider [react-fa](https://github.com/andreypopp/react-fa), [chevron-right](https://fortawesome.github.io/Font-Awesome/icon/chevron-right/) and [chevron-left](https://fortawesome.github.io/Font-Awesome/icon/chevron-left/).

**Comment by bobiblazeski** [comment]
Added font awesome chevrons, extracted carousel style into separate file https://github.com/bobiblazeski/react-3d-carousel/commit/eb35efa34776f43d649bfb831e7e5ff16d8e6d05
Icons could be easily changed by customizing https://github.com/bobiblazeski/react-3d-carousel/blob/master/static/style.css selectors  .react-3d-carousel   .prev:before & .react-3d-carousel  .next:before
