### ISSUE TITLE
Easing functions should be extracted into separate project

### ISSUE THREAD

**Issue by bobiblazeski** [bobiblazeski/react-3d-carousel#3]
Carousel.jsx - Maybe same makes sense for easing. I can see you have a very nice collection of defaults, though.

**Comment by bebraw** [comment]
Can you benefit from [animate-plus](https://github.com/bendc/animate-plus)? Looks like there are tons of easing functions there.

**Comment by bobiblazeski** [comment]
They seem like the same Robert Penner functions. I've extracted mine at https://github.com/bobiblazeski/ease-functions . If you need anything more contributions are welcome.
