### ISSUE TITLE
missing file js/Carousel.js

### ISSUE THREAD

**Issue by rsamec** [bobiblazeski/react-3d-carousel#6]
First off I really like your project.

I try to use it via npm -> npm install react-3d-carousel
but in package.json - "main": "js/Carousel.js", but the file Carousel.js is missing.

**Comment by bebraw** [comment]
@bobiblazeski It's probably neatest to solve this with a prepublish script like this:

``` json
    "prepublish": "babel ./src --out-dir ./js",
```

You should have `babel` and `babel-core` as dev deps for this to work. Also add `./js` to `.gitignore` so `git status` looks clean.

**Comment by bobiblazeski** [comment]
@rsamec Thank you for the kind words. It needs some work to make it usable so feedback is wellcome. I republished with compiled JavaScript files. Try it now how it works.

@bobiblazeski Thanks for the tip. I had some problems with adding ./js to gitignore as it seems that ./js folder added in npmignore and new version doesn't contain ./js folder, so the demo throws same error. I haven't used prepublish before, so probably I'm forgetting something.

**Comment by rsamec** [comment]
It works like a charm with compiled Javascript files.Thanks.
